[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day1 = "6m3e17LB3YhXvzax97TNxGwUL6nRbFRKjGYgXWxXLPcD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/aizee/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
